- name: test case
  hosts: localhost
  roles:
    - role: get_info
  # tasks:
  #   - name: Delay between Task 1 and Task 2
  #     pause:
  #       seconds: 5 


- name: SSM Installation
  hosts: webserver
  become: true
  roles:
    - role: ssm
    - role: cloudwatch
  