---
- name: Download CloudWatch Agent for ubuntu
  get_url:
    url: "https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
    dest: "{{ cwa_temp_path }}/amazon-cloudwatch-agent.deb"
  when: ansible_os_family == 'Debian'  

- name: Install CloudWatch Agent for ubuntu
  become: true
  apt:
    deb: "{{ cwa_temp_path }}/amazon-cloudwatch-agent.deb"
    state: present
  when: ansible_os_family == 'Debian'

- name: Configure {{ cwa_package }} for ubuntu
  become: true
  template:
    src: cloudwatch-config.json.j2
    dest: "{{ cwa_agent_config_file }}"
  notify:
    - Restart CloudWatch Agent


- name: Start and enable {{ cwa_package }} service for ubuntu
  become: true
  systemd:
    name: "{{ cwa_package }}"
    state: started
    enabled: yes


- name: Delay after CloudWatch Agent configuration
  pause:
    seconds: 5
