---
- name: Download {{ cwa_package }}.rpm.sig file
  get_url:
    url: "{{ cwa_package_signature }}"
    dest: "{{ cwa_temp_path }}/{{ cwa_package }}.rpm.sig"
    timeout: "{{ cwa_global_downloads_timeout }}"
  when: ansible_os_family == 'RedHat'
  
- name: Download {{ cwa_package }}.rpm file
  get_url:
    url: "{{ cwa_package_url }}"
    dest: "{{ cwa_temp_path }}/{{ cwa_package }}.rpm"
    timeout: "{{ cwa_global_downloads_timeout }}"
  when: ansible_os_family == 'RedHat'

- name: Verify {{ cwa_package }} package signature
  command: gpg --verify {{ cwa_package }}.rpm.sig {{ cwa_package }}.rpm
  register: verified_sig
  failed_when: "'BAD' in verified_sig.stderr"
  changed_when: false
  args:
    chdir: "{{ cwa_temp_path }}"

# - name: Download CloudWatch Agent for redhat
#   get_url:
#     url: "https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm"
#     dest: "/tmp/amazon-cloudwatch-agent.rpm"
#   when: ansible_os_family == 'RedHat'

- name: Install CloudWatch Agent for redhat
  become: true
  become_method: sudo 
  yum:
    name: "{{ cwa_temp_path }}/amazon-cloudwatch-agent.rpm"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Configure CloudWatch Agent for redhat
  become: true
  template:
    src: cloudwatch-config.json.j2
    dest: "{{ cwa_agent_config_file }}"
  notify:
    - Restart CloudWatch Agent

- name: Start and enable CloudWatch Agent service for redhat
  become: true
  systemd:
    name: "{{ cwa_package }}"
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: Delay after CloudWatch Agent configuration
  pause:
    seconds: 5
  when: ansible_os_family == 'RedHat'